[build]
  # Build command for Nuxt 3
  command = "npm run build"
  
  # Publish directory for Nuxt 3 - using actual output directory
  publish = "dist"

[build.environment]
  # Node.js version - Updated to Node 20 for Nuxt 3.18.1 compatibility
  NODE_VERSION = "20"
  
  # NPM version (optional)
  NPM_VERSION = "10"

# No explicit redirects needed - Nuxt 3 Netlify preset handles routing automatically

# Headers for better performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/_nuxt/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache fonts
[[headers]]
  for = "/fonts/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
